spring:
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 484559468446-5gh40trbfrm81jpr8gg3v81qpfgbo9m2.apps.googleusercontent.com
              clientSecret: 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
              scope:
                - email
                - profile
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: 
      - http://localhost:3000
      - http://localhost:3001
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect